### ISSUE TITLE
How can I use owfont in Android?

### ISSUE THREAD

**Issue by fevziomurtekin** [websygen/owfont#6]
Hi, 
I want to owfont icons in Android application but I don't know usage in Android application. 
I have the **ED31** code and the owfont-regular.otf font. How should I send it?

**Comment by websygen** [comment]
> 
> 
> Hi,
> I want to owfont icons in Android application but I don't know usage in Android application.
> I have the **ED31** code and the owfont-regular.otf font. How should I send it?

Haven't use it in Android but you can check something like that
[https://stackoverflow.com/questions/37959751/how-to-use-font-awesome-icon-in-android-application](url) as owfont is based on font-awesome (early version)

**Comment by fevziomurtekin** [comment]
Thank you so much. 
`&#xED31;`  it worked.
