### ISSUE TITLE
Make icons available as SVGs.

### ISSUE THREAD

**Issue by KonradStuewe** [websygen/owfont#8]
I would really like to use these icons in a project I'm working on, but since it isn't using HTML/CSS, I can't really use the provided font files.

Would it be possible to also release them as PNGs or even SVGs?

It would be greatly appreciated!

**Comment by websygen** [comment]
@KonradStuewe this project is very old and I don't have my original SVG files
you can extract the SVGs as separate files using some online service
https://icomoon.io/app for example is free and capable to export single svg from file
just import the font from the project

also the svg font file contains all the paths
[https://github.com/websygen/owfont/blob/master/fonts/owfont-regular.svg](https://github.com/websygen/owfont/blob/master/fonts/owfont-regular.svg)
